# version: '3.8'   
 
services:   
  backend:   
    container_name: backend 
    build: .   
    command: python manage.py runserver 0.0.0.0:8000   
    volumes:   
      - ./core:/app   
    ports:   
      - "8000:8000" 

   
#docker-compose up --build